Models/ErrorViewModel.cs
using System;

namespace MFA_Blog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MFA_Blog.Models
{
    public class UserModel
    {
        private int _userId;
        private string _name;
        private string _surname;
        private string _email;
        private string _password;

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int UserId { get => _userId; set => _userId = value; }
        public string Name { get => _name; set => _name = value; }
        public string Surname { get => _surname; set => _surname = value; }
        public string Email { get => _email; set => _email = value; }
        public string Password { get => _password; set => _password = value; }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MFA_Blog.Controllers
{
    [Route("admin")]
    public class AdminController : Controller
    {
        [HttpGet("dashboard")]
        public IActionResult Dashbıard()
        {
            return View();
        }
    }
}

Controllers/AuthtController.cs
using MFA_Blog.Dto;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MFA_Blog.Controllers
{
    [Route("auth")]
    public class AuthController : Controller
    {
        [HttpGet("login")]
        public IActionResult Login(string requestPath)
        {
            ViewBag.RequestPath = requestPath ?? "/";
            return View();
        }

        [HttpPost("login")]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            return await SignInUser(loginDto);
        }

        [Route("logout")]
        public async Task<IActionResult> Logout(string requestPath)
        {
            await HttpContext.SignOutAsync(scheme: "MFASecurityScheme");

            return RedirectToAction("Login");
        }


        [Route("loginexternal/{id}")]
        public Task LogInExternal(string id)
        {
            return HttpContext.ChallengeAsync(id, new AuthenticationProperties { RedirectUri = "/auth/registerexternal" });
        }

        [Route("registerexternal")]
        public async Task<IActionResult> RegisterExternal(string authprovider)
        {
            var authResult = await HttpContext.AuthenticateAsync("TempCookie");
            if (!authResult.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }

            var facebookUserClaims = authResult.Principal.Claims;
            await HttpContext.SignInAsync(authResult.Principal);
            //Bu kısımda bilgileri modele ekleyip register sayfasına yönlendirip ilgili alanları doldurup kişinin kaydolmasını sağlayabiliriz.
            return Redirect("/");
        }

        [Route("registerexternal/{id}")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> RegisterExternal(string id, RegisterDto registerDto)
        {
            var authResult = await HttpContext.AuthenticateAsync("TempCookie");
            if (!authResult.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(registerDto);
            }

            //Veri tabanına kaydet ve Login et
            //var user = await userService.AddExternal(authResult.Principal.FindFirstValue(ClaimTypes.NameIdentifier), registerDto.Name, registerDto.Email);
            LoginDto loginDto = new LoginDto()
            {
                Username = registerDto.Email,
            };


            return await SignInExternal(loginDto);
        }

        private async Task<IActionResult> SignInExternal(LoginDto loginDto)
        {
            await HttpContext.SignOutAsync("TempCookie");
            return await SignInUser(loginDto);
        }

        private async Task<IActionResult> SignInUser(LoginDto loginDto)
        {

            if (!IsAuthentic(loginDto.Username, loginDto.Password))
                return View();

            // create claims
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, loginDto.Username),
                new Claim(ClaimTypes.Email, loginDto.Username)
            };

            // create identity
            ClaimsIdentity identity = new ClaimsIdentity(claims, "cookie");

            // create principal
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);

            // sign-in
            await HttpContext.SignInAsync(
                    scheme: "MFASecurityScheme",
                    principal: principal,
                    properties: new AuthenticationProperties
                    {
                        IsPersistent = loginDto.RememberMe, // for 'remember me' feature
                        ExpiresUtc = DateTime.UtcNow.AddMinutes(20)
                    });

            return Redirect(loginDto.RequestPath ?? "/");
        }

        public IActionResult Access()
        {
            return View();
        }


        private bool IsAuthentic(string username, string password)
        {
            return (username == "nurullah.yayan@gmail.com" && password == "123123");
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MFA_Blog.Controllers
{
    public class ContactController : Controller
    {

        [Route("Contact")]
        public IActionResult Contact()
        {
            return View();
        }
    }
}

Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MFA_Blog.Controllers
{
    [Route("admin")]
    public class PostController : Controller
    {
        [HttpGet("post/list")]
        public IActionResult PostList()
        {
            return View();
        }

        [HttpGet("post/add")]
        public IActionResult PostAdd()
        {
            return View("AddOrUpdatePost");
        }

        [HttpGet("post/update")]
        public IActionResult PostUpdate(int postId)
        {
            return View("AddOrUpdatePost");
        }
    }
}

Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MFA_Blog.Controllers
{
    public class StoryController : Controller
    {
        public IActionResult Story()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MFA_Blog.Dto;
using MFA_Blog.Service;
using Microsoft.AspNetCore.Mvc;

namespace MFA_Blog.Controllers
{
    [Route("admin")]
    public class UserController : Controller
    {
        IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet("user/list")]
        public IActionResult UserList()
        {
            List<UserDto> userDtos = _userService.GetUsers();

            return View(userDtos);
        }

        [HttpGet("user/add")]
        public IActionResult AddUser()
        {
            return View("AddOrUpdateUser");
        }

        [HttpPost("user/add")]
        public IActionResult AddUser(UserDto user, string password)
        {
            if (user.UserId > 0)
            {
                _userService.UpdateUser(user,password);
            }
            else
            {
                _userService.AddUser(user, password);
            }


            return View("AddOrUpdateUser", user);
        }

        [HttpGet("user/edit/{userId}")]
        public IActionResult EditUser(int userId)
        {
            UserDto userDto = _userService.GetUserById(userId);

            return View("AddOrUpdateUser", userDto);
        }
    }
}

Views/Contact/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="contact-container container clearfix story">
    <h4 style="text-align:right;">
        CLICK Here > <a style="color: red;" href="/story">Go Back</a>
    </h4>
    <h1 style="margin-bottom:30px;">My Profile</h1>
    <div class="col-md-4">
        <img src="~/images/my/mfakdeniz.jpeg" alt="Muhammet Faruk AKDENİZ" style="width:100%" />
    </div>

    <div class="col-md-8">
        <div class="form-group">
            <label>Name and Surname</label>
            <label class="form-control">
                Muhammet Faruk AKDENIZ
            </label>
        </div>

        <div class="form-group">
            <label>Student Number</label>
            <label class="form-control">
                18120101007
            </label>
        </div>

        <div class="form-group">
            <label>Class</label>
            <label class="form-control">
                B5
            </label>
        </div>

    </div>



</div>

Views/Post/AddOrUpdatePost.cshtml
@{
    ViewData["Title"] = "AddOrUpdateUser";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- END: Subheader -->
    <div class="m-content">
        <div class="row">
            <div class="col-md-6">
                <!--begin::Portlet-->
                <div class="m-portlet m-portlet--tab">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Kullanıcı Ekle/Düzenle
                                </h3>
                            </div>
                        </div>
                    </div>

                    <!--begin::Form-->
                    <form class="m-form m-form--fit m-form--label-align-right">
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group m--margin-top-10">
                                <div class="alert m-alert m-alert--default" role="alert">
                                    The example form below demonstrates common HTML form elements that receive updated styles from Bootstrap with additional classes.
                                </div>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="email" class="form-control m-input" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                                <span class="m-form__help">We'll never share your email with anyone else.</span>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="password" class="form-control m-input" id="exampleInputPassword1" placeholder="Password">
                            </div>
                            <div class="form-group m-form__group">
                                <label>Static:</label>
                                <p class="form-control-static">email@example.com</p>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleSelect1">Example select</label>
                                <select class="form-control m-input" id="exampleSelect1">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleSelect2">Example multiple select</label>
                                <select multiple="" class="form-control m-input" id="exampleSelect2">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleTextarea">Example textarea</label>
                                <textarea class="form-control m-input" id="exampleTextarea" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions">
                                <button type="reset" class="btn btn-primary">Submit</button>
                                <button type="reset" class="btn btn-secondary">Cancel</button>
                            </div>
                        </div>
                    </form>

                    <!--end::Form-->
                </div>

                <!--end::Portlet-->


            </div>

        </div>
    </div>
</div>

Views/Post/PostList.cshtml
@{
    ViewData["Title"] = "PostList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="m-grid__item m-grid__item--fluid m-wrapper">

    <!-- END: Subheader -->
    <div class="m-content">
        <div class="m-alert m-alert--icon m-alert--air m-alert--square alert alert-dismissible m--margin-bottom-30" role="alert">
            <div class="m-alert__icon">
                <i class="flaticon-exclamation m--font-brand"></i>
            </div>
            <div class="m-alert__text">
                DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon the foundations of progressive enhancement, and will add advanced interaction controls to any HTML table. For more info see
                <a href="https://datatables.net/"
                   target="_blank">the official home</a> of the plugin.
            </div>
        </div>
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Basic Example
                        </h3>
                    </div>
                </div>
                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="#" class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>New record</span>
                                </span>
                            </a>
                        </li>
                        <li class="m-portlet__nav-item"></li>
                        <li class="m-portlet__nav-item">
                            <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push" m-dropdown-toggle="hover" aria-expanded="true">
                                <a href="#" class="m-portlet__nav-link btn btn-lg btn-secondary  m-btn m-btn--icon m-btn--icon-only m-btn--pill  m-dropdown__toggle">
                                    <i class="la la-ellipsis-h m--font-brand"></i>
                                </a>
                                <div class="m-dropdown__wrapper">
                                    <span class="m-dropdown__arrow m-dropdown__arrow--right m-dropdown__arrow--adjust"></span>
                                    <div class="m-dropdown__inner">
                                        <div class="m-dropdown__body">
                                            <div class="m-dropdown__content">
                                                <ul class="m-nav">
                                                    <li class="m-nav__section m-nav__section--first">
                                                        <span class="m-nav__section-text">Quick Actions</span>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-share"></i>
                                                            <span class="m-nav__link-text">Create Post</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-chat-1"></i>
                                                            <span class="m-nav__link-text">Send Messages</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-multimedia-2"></i>
                                                            <span class="m-nav__link-text">Upload File</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__section">
                                                        <span class="m-nav__section-text">Useful Links</span>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-info"></i>
                                                            <span class="m-nav__link-text">FAQ</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__item">
                                                        <a href="" class="m-nav__link">
                                                            <i class="m-nav__link-icon flaticon-lifebuoy"></i>
                                                            <span class="m-nav__link-text">Support</span>
                                                        </a>
                                                    </li>
                                                    <li class="m-nav__separator m-nav__separator--fit m--hide">
                                                    </li>
                                                    <li class="m-nav__item m--hide">
                                                        <a href="#" class="btn btn-outline-danger m-btn m-btn--pill m-btn--wide btn-sm">Submit</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="m-portlet__body">

                <!--begin: Datatable -->
                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                        <tr>
                            <th>RecordID</th>
                            <th>OrderID</th>
                            <th>Country</th>
                            <th>ShipCity</th>
                            <th>ShipAddress</th>
                            <th>CompanyAgent</th>
                            <th>CompanyName</th>
                            <th>ShipDate</th>
                            <th>Status</th>
                            <th>Type</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>61715-075</td>
                            <td>China</td>
                            <td>Tieba</td>
                            <td>746 Pine View Junction</td>
                            <td>Nixie Sailor</td>
                            <td>Gleichner, Ziemann and Gutkowski</td>
                            <td>2/12/2018</td>
                            <td>3</td>
                            <td>2</td>
                            <td>
                                <span class="dropdown">
                                    <a href="#" class="btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" data-toggle="dropdown" aria-expanded="false">
                                        <i class="la la-ellipsis-h"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-196px, 27px, 0px); top: 0px; left: 0px; will-change: transform;">
                                        <a class="dropdown-item" href="#"><i class="la la-edit"></i> Edit Details</a>
                                        <a class="dropdown-item" href="#"><i class="la la-leaf"></i> Update Status</a>
                                        <a class="dropdown-item" href="#"><i class="la la-print"></i> Generate Report</a>
                                    </div>
                                </span>
                                <a href="#" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="View">
                                    <i class="la la-edit"></i>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MFA_Blog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="false" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Story" asp-action="Story" class="navbar-brand">MFA_Blog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Home">Home</a></li>*@
                    <li><a asp-area="" asp-controller="Story" asp-action="Story">Story</a></li>
                    <li><a asp-area="" asp-controller="Contact" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Auth" asp-action="Login">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MFA_Blog</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/User/AddOrUpdateUser.cshtml
@model UserDto
@{
    ViewData["Title"] = "AddOrUpdateUser";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="m-grid__item m-grid__item--fluid m-wrapper">
    <!-- END: Subheader -->
    <div class="m-content">
        <div class="row">
            <div class="col-md-6">
                <!--begin::Portlet-->
                <div class="m-portlet m-portlet--tab">
                    <div class="m-portlet__head">
                        <div class="m-portlet__head-caption">
                            <div class="m-portlet__head-title">
                                <span class="m-portlet__head-icon m--hide">
                                    <i class="la la-gear"></i>
                                </span>
                                <h3 class="m-portlet__head-text">
                                    Kullanıcı Ekle/Düzenle
                                </h3>
                            </div>
                        </div>
                    </div>


                    <!--begin::Form-->
                    <form class="m-form m-form--fit m-form--label-align-right" asp-controller="admin" asp-action="user/add" method="post" novalidate>
                        <input type="hidden" asp-for="UserId">
                        <div class="m-portlet__body">
                            <div class="form-group m-form__group m--margin-top-10">
                                <div class="alert m-alert m-alert--default" role="alert">
                                    The example form below demonstrates common HTML form elements that receive updated styles from Bootstrap with additional classes.
                                </div>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="text" class="form-control m-input" asp-for="Name" aria-describedby="emailHelp" placeholder="Enter Name">
                                <span class="m-form__help">We'll never share your email with anyone else.</span>
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="text" class="form-control m-input" asp-for="Surname" aria-describedby="emailHelp" placeholder="Enter Surname">
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="text" class="form-control m-input" asp-for="Email" aria-describedby="emailHelp" placeholder="Enter Email">
                            </div>
                            <div class="form-group m-form__group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="password" class="form-control m-input" name="password" aria-describedby="emailHelp" placeholder="Enter Surname">
                            </div>

                        </div>
                        <div class="m-portlet__foot m-portlet__foot--fit">
                            <div class="m-form__actions">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="/admin/user/list" class="btn btn-secondary">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </form>

                    <!--end::Form-->
                </div>

                <!--end::Portlet-->


            </div>

        </div>
    </div>
</div>